name: cryptostat

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Action - checkout
      uses: actions/checkout@v3

    - name: Check package version
      run: node -v && yarn -v

    - name: Install dependencies
      run: rm -rf node_modules && yarn install --frozen-lockfile --frozen-dependencies

    # - name: Restart pm2
    #   run: pm2 restart cryptostat-server