name: keepcoin

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Action - checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn install --immutable

    - name: import env file
      run: cp ~/env-files/.keepcoin-dev.env .env

    - name: build
      run: yarn build

    - name: Restart pm2
      run: /home/ubuntu/.nvm/versions/node/v18.17.1/bin/pm2 restart keepcoin-dev-server