name: keepcoin

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Action - checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn install --immutable

    # - name: Restart pm2
    #   run: pm2 restart cryptostat-server